dict = {
    "a": {
        "nombre_entidad": "ICBF SEDE NACIONAL",
        "nit_entidad": "899999239",
        "departamento": "Distrito Capital de Bogotá",
        "ciudad": "No Definido",
        "localizaci_n": "Colombia, Bogotá, No Definido",
        "orden": "Nacional",
        "sector": "Inclusión Social y Reconciliación",
        "rama": "Ejecutivo",
        "entidad_centralizada": "Centralizada",
        "proceso_de_compra": "CO1.BDOS.3762139",
        "id_contrato": "CO1.PCCNTR.4412268",
        "referencia_del_contrato": "01002412023",
        "estado_contrato": "Cerrado",
        "codigo_de_categoria_principal": "V1.80111600",
        "descripcion_del_proceso": "PRESTAR SERVICIOS PROFESIONALES AL GRUPO DE GESTIÓN DE BIENES EN EL SEGUIMIENTO AL REGISTRO Y CONTROL DE LA PROPIEDAD PLANTA Y EQUIPO EN EL MARCO DE LA NORMATIVIDAD VIGENTE; QUE PERMITA REALIZAR UN ADECUADO CIERRE CONTABLE DE LA VIGENCIA 2023; ASÍ COMO TAMBIÉN; APOYAR LA RECEPCIÓN; GESTIÓN; SEGUIMIE",
        "tipo_de_contrato": "Prestación de servicios",
        "modalidad_de_contratacion": "Contratación directa",
        "justificacion_modalidad_de": "Servicios profesionales y apoyo a la gestión",
        "fecha_de_firma": "2023-01-19T00:00:00.000",
        "fecha_de_inicio_del_contrato": "2023-01-19T00:00:00.000",
        "fecha_de_fin_del_contrato": "2023-12-31T00:00:00.000",
        "condiciones_de_entrega": "NXTWY.DLVY.6",
        "tipodocproveedor": "Cédula de Ciudadanía",
        "documento_proveedor": "1110575392",
        "proveedor_adjudicado": "LINA PAOLA RIVILLAS BOHÓRQUEZ",
        "es_grupo": "No",
        "es_pyme": "No",
        "habilita_pago_adelantado": "No",
        "liquidaci_n": "No",
        "obligaci_n_ambiental": "No",
        "obligaciones_postconsumo": "No",
        "reversion": "No",
        "origen_de_los_recursos": "Distribuido",
        "destino_gasto": "Inversión",
        "valor_del_contrato": "42162933",
        "valor_de_pago_adelantado": "0",
        "valor_facturado": "27332367",
        "valor_pendiente_de_pago": "14830566",
        "valor_pagado": "27332367",
        "valor_amortizado": "0",
        "valor_pendiente_de": "0",
        "valor_pendiente_de_ejecucion": "14830566",
        "saldo_cdp": "4941770132",
        "saldo_vigencia": "0",
        "espostconflicto": "No",
        "dias_adicionados": "0",
        "puntos_del_acuerdo": "No aplica",
        "pilares_del_acuerdo": "No aplica",
        "urlproceso": {
            "url": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.3769758&isFromPublicArea=True&isModal=true&asPopupView=true"
        },
        "nombre_representante_legal": "PAOLA RIVILLAS",
        "nacionalidad_representante_legal": "CO",
        "domicilio_representante_legal": "No Definido",
        "tipo_de_identificaci_n_representante_legal": "Cédula de Ciudadanía",
        "identificaci_n_representante_legal": "1110575392",
        "g_nero_representante_legal": "Mujer",
        "presupuesto_general_de_la_nacion_pgn": "42162933",
        "sistema_general_de_participaciones": "0",
        "sistema_general_de_regal_as": "0",
        "recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_": "0",
        "recursos_de_credito": "0",
        "recursos_propios": "0",
        "ultima_actualizacion": "2026-04-21T00:00:00.000",
        "codigo_entidad": "700087026",
        "codigo_proveedor": "713956167",
        "objeto_del_contrato": "PRESTAR SERVICIOS PROFESIONALES AL GRUPO DE GESTIÓN DE BIENES EN EL SEGUIMIENTO AL REGISTRO Y CONTROL DE LA PROPIEDAD PLANTA Y EQUIPO EN EL MARCO DE LA NORMATIVIDAD VIGENTE; QUE PERMITA REALIZAR UN ADECUADO CIERRE CONTABLE DE LA VIGENCIA 2023; ASÍ COMO TAMBIÉN; APOYAR LA RECEPCIÓN; GESTIÓN; SEGUIMIENTO Y CONTROL DE LAS DONACIONES Y OFRECIMIENTOS REALIZADOS AL ICBF DURANTE LA VIGENCIA 2023.",
        "duraci_n_del_contrato": "344 Dia(s)",
        "nombre_del_banco": "BANCO CAJA SOCIAL",
        "tipo_de_cuenta": "Ahorros",
        "n_mero_de_cuenta": "24100552399",
        "el_contrato_puede_ser_prorrogado": "No",
        "nombre_ordenador_del_gasto": "Maria Teresa Salamanca Acosta",
        "tipo_de_documento_ordenador_del_gasto": "Cédula de Ciudadanía",
        "n_mero_de_documento_ordenador_del_gasto": "51809990",
        "nombre_supervisor": "LUZ HELENA MEJIA ZULUAGA",
        "tipo_de_documento_supervisor": "Cédula de Ciudadanía",
        "n_mero_de_documento_supervisor": "52208179",
        "nombre_ordenador_de_pago": "No definido",
        "tipo_de_documento_ordenador_de_pago": "No definido",
        "n_mero_de_documento_ordenador_de_pago": "No definido",
        "documentos_tipo": "No",
        "descripcion_documentos_tipo": "No definido",
    },
    "b": {
        "nombre_entidad": "CORPORACION AUTONOMA REGIONAL DE RISARALDA",
        "nit_entidad": "891410354",
        "departamento": "Risaralda",
        "ciudad": "Pereira",
        "localizaci_n": "Colombia,  Risaralda ,  Pereira",
        "orden": "Corporación Autónoma",
        "sector": "Ambiente y Desarrollo Sostenible",
        "rama": "Corporación Autónoma",
        "entidad_centralizada": "Centralizada",
        "proceso_de_compra": "CO1.BDOS.2551782",
        "id_contrato": "CO1.PCCNTR.3233914",
        "referencia_del_contrato": "CO1.PCCNTR.3233914",
        "estado_contrato": "Cerrado",
        "codigo_de_categoria_principal": "V1.77111500",
        "descripcion_del_proceso": "Apoyar profesionalmente a la Corporación Autónoma Regional de Risaralda- CARDER en la dinamización y articulación de procesos con las comunidades étnicas; y las instituciones aliadas; en el marco del acompañamiento a la gestión de los instrumentos de planificación propia y comunitaria; para el forta",
        "tipo_de_contrato": "Prestación de servicios",
        "modalidad_de_contratacion": "Contratación directa",
        "justificacion_modalidad_de": "Servicios profesionales y apoyo a la gestión",
        "fecha_de_firma": "2022-01-19T00:00:00.000",
        "fecha_de_inicio_del_contrato": "2022-01-20T00:00:00.000",
        "fecha_de_fin_del_contrato": "2022-10-19T00:00:00.000",
        "condiciones_de_entrega": "NXTWY.DLVY.6",
        "tipodocproveedor": "Cédula de Ciudadanía",
        "documento_proveedor": "42144955",
        "proveedor_adjudicado": "Carmen Juliana Trujillo Trujillo",
        "es_grupo": "No",
        "es_pyme": "No",
        "habilita_pago_adelantado": "No",
        "liquidaci_n": "No",
        "obligaci_n_ambiental": "No",
        "obligaciones_postconsumo": "No",
        "reversion": "No",
        "origen_de_los_recursos": "Recursos Propios",
        "destino_gasto": "Inversión",
        "valor_del_contrato": "25857000",
        "valor_de_pago_adelantado": "0",
        "valor_facturado": "25857000",
        "valor_pendiente_de_pago": "0",
        "valor_pagado": "25857000",
        "valor_amortizado": "0",
        "valor_pendiente_de": "0",
        "valor_pendiente_de_ejecucion": "0",
        "saldo_cdp": "25857000",
        "saldo_vigencia": "0",
        "espostconflicto": "No",
        "dias_adicionados": "0",
        "puntos_del_acuerdo": "No aplica",
        "pilares_del_acuerdo": "No aplica",
        "urlproceso": {
            "url": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.2553819&isFromPublicArea=True&isModal=true&asPopupView=true"
        },
        "nombre_representante_legal": "Carmen Juliana Trujillo Trujillo",
        "nacionalidad_representante_legal": "CO",
        "domicilio_representante_legal": "Estrato V  * Ubicación  pereira  * \t   País COLOMBIA  * Correo electrónico cajuly80@yahoo.com  * Teléfono Celular 3216258212  * Nivel Educativo Posgrado  *   Configuración Usar configuración predeterminada\t\t  Zona horaria\t (UTC-05:00) Bogotá, Lima, Quito  *\t  Idioma\t Español (Colombia)  *\t  Configuración regional\t Spanish (Colombia)  *\t   Ejemplo configuración regional seleccionada Formato de fecha y hora\t19/10/2022 4:48 PM\t  Formato de número\t9999.999.999,999\t     Seguridad de la información Pregunta de seguridad\t ¿Cuál es el nombre de su abuelo?  *\t  Respuesta\t pacho trujillo   *\t  SMS para recuperar la contraseña\t 3216258212  *\t  Cancelar\t \t\t © VORTAL 2019Términos de usoNormativaSoporte RemotoAyuda Español (Colombia) 018000-52-0808www.colombiacompra.gov.co/soporte Lunes a Viernes 7:00 a.m. a 7:00 p.m.",
        "tipo_de_identificaci_n_representante_legal": "Cédula de Ciudadanía",
        "identificaci_n_representante_legal": "42144955",
        "g_nero_representante_legal": "Mujer",
        "presupuesto_general_de_la_nacion_pgn": "0",
        "sistema_general_de_participaciones": "0",
        "sistema_general_de_regal_as": "0",
        "recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_": "0",
        "recursos_de_credito": "0",
        "recursos_propios": "25857000",
        "ultima_actualizacion": "2022-07-19T00:00:00.000",
        "codigo_entidad": "702481052",
        "codigo_proveedor": "703142562",
        "objeto_del_contrato": "Apoyar profesionalmente a la Corporación Autónoma Regional de Risaralda- CARDER en la dinamización y articulación de procesos con las comunidades étnicas; y las instituciones aliadas; en el marco del acompañamiento a la gestión de los instrumentos de planificación propia y comunitaria; para el fortalecimiento de la gestión ambiental territorial.",
        "duraci_n_del_contrato": "9 Mes(es)",
        "nombre_del_banco": "Caja Social",
        "tipo_de_cuenta": "Ahorros",
        "n_mero_de_cuenta": "24047269013",
        "el_contrato_puede_ser_prorrogado": "No",
        "nombre_ordenador_del_gasto": "JULIO CESAR GOMEZ SALAZAR",
        "tipo_de_documento_ordenador_del_gasto": "Cédula de Ciudadanía",
        "n_mero_de_documento_ordenador_del_gasto": "10110976",
        "nombre_supervisor": "CARLOS FABIAN JARAMILLO RÍOS",
        "tipo_de_documento_supervisor": "Cédula de Ciudadanía",
        "n_mero_de_documento_supervisor": "10144982",
        "nombre_ordenador_de_pago": "No definido",
        "tipo_de_documento_ordenador_de_pago": "No definido",
        "n_mero_de_documento_ordenador_de_pago": "No definido",
        "documentos_tipo": "No",
        "descripcion_documentos_tipo": "No definido",
    },
    "c": {
        "nombre_entidad": "GOBERNACIÓN DE BOYACÁ",
        "nit_entidad": "891800498",
        "departamento": "Boyacá",
        "ciudad": "Tunja",
        "localizaci_n": "Colombia,  Boyacá ,  Tunja",
        "orden": "Territorial",
        "sector": "Servicio Público",
        "rama": "Ejecutivo",
        "entidad_centralizada": "Centralizada",
        "proceso_de_compra": "CO1.BDOS.1237261",
        "id_contrato": "CO1.PCCNTR.1550803",
        "referencia_del_contrato": "CONTRATO INTERADMINISTRATIVO N°  \tDE 2020",
        "estado_contrato": "Cerrado",
        "codigo_de_categoria_principal": "V1.85101604",
        "descripcion_del_proceso": "PRESTACIÓN DE SERVICIOS PARA REALIZAR LAS ACCIONES DEL PLAN DE INTERVENCIONES COLECTIVAS.",
        "tipo_de_contrato": "Prestación de servicios",
        "modalidad_de_contratacion": "Contratación directa",
        "justificacion_modalidad_de": "Servicios profesionales y apoyo a la gestión",
        "fecha_de_firma": "2020-05-28T00:00:00.000",
        "fecha_de_inicio_del_contrato": "2020-06-01T00:00:00.000",
        "fecha_de_fin_del_contrato": "2020-12-31T00:00:00.000",
        "condiciones_de_entrega": "A convenir",
        "tipodocproveedor": "NIT",
        "documento_proveedor": "826002890",
        "proveedor_adjudicado": "ESE CENTRO DE SALUD TOTA",
        "es_grupo": "No",
        "es_pyme": "No",
        "habilita_pago_adelantado": "No Definido",
        "liquidaci_n": "No",
        "obligaci_n_ambiental": "No",
        "obligaciones_postconsumo": "No",
        "reversion": "No",
        "origen_de_los_recursos": "Distribuido",
        "destino_gasto": "Inversión",
        "valor_del_contrato": "28190045",
        "valor_de_pago_adelantado": "0",
        "valor_facturado": "0",
        "valor_pendiente_de_pago": "28190045",
        "valor_pagado": "0",
        "valor_amortizado": "0",
        "valor_pendiente_de": "0",
        "valor_pendiente_de_ejecucion": "28190045",
        "saldo_cdp": "28190045",
        "saldo_vigencia": "0",
        "espostconflicto": "No",
        "dias_adicionados": "0",
        "puntos_del_acuerdo": "No aplica",
        "pilares_del_acuerdo": "No aplica",
        "urlproceso": {
            "url": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.1236001&isFromPublicArea=True&isModal=true&asPopupView=true"
        },
        "nombre_representante_legal": "RODRIGO NOMESQUE CAMPOS",
        "nacionalidad_representante_legal": "CO",
        "domicilio_representante_legal": "No Definido",
        "tipo_de_identificaci_n_representante_legal": "Sin Descripcion",
        "identificaci_n_representante_legal": "Sin Descripcion",
        "g_nero_representante_legal": "Mujer",
        "presupuesto_general_de_la_nacion_pgn": "0",
        "sistema_general_de_participaciones": "28190045",
        "sistema_general_de_regal_as": "0",
        "recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_": "0",
        "recursos_de_credito": "0",
        "recursos_propios": "0",
        "ultima_actualizacion": "2022-06-02T00:00:00.000",
        "codigo_entidad": "702727819",
        "codigo_proveedor": "709720338",
        "objeto_del_contrato": "PRESTACIÓN DE SERVICIOS PARA REALIZAR LAS ACCIONES DEL PLAN DE INTERVENCIONES COLECTIVAS.",
        "duraci_n_del_contrato": "7 Mes(es)",
        "nombre_del_banco": "BANCO AV VILLAS",
        "tipo_de_cuenta": "Corriente",
        "n_mero_de_cuenta": "720147230",
        "el_contrato_puede_ser_prorrogado": "Si",
        "fecha_de_notificaci_n_de_prorrogaci_n": "2020-12-23T00:00:00.000",
        "nombre_ordenador_del_gasto": "JOSE FERNANDO CAMARGO BELTRAN",
        "tipo_de_documento_ordenador_del_gasto": "Cédula de Ciudadanía",
        "n_mero_de_documento_ordenador_del_gasto": "6765994",
        "nombre_supervisor": "No definido",
        "tipo_de_documento_supervisor": "No definido",
        "n_mero_de_documento_supervisor": "No definido",
        "nombre_ordenador_de_pago": "No definido",
        "tipo_de_documento_ordenador_de_pago": "No definido",
        "n_mero_de_documento_ordenador_de_pago": "No definido",
        "documentos_tipo": "No",
        "descripcion_documentos_tipo": "No definido",
    },
    "d": {
        "nombre_entidad": "EMPRESA AUTONOMA GUATAPE",
        "nit_entidad": "800105497",
        "departamento": "Antioquia",
        "ciudad": "Guatape",
        "localizaci_n": "Colombia,  Antioquia ,  Guatape",
        "orden": "Territorial",
        "sector": "No aplica/No pertenece",
        "rama": "Ejecutivo",
        "entidad_centralizada": "Centralizada",
        "proceso_de_compra": "CO1.BDOS.4227862",
        "id_contrato": "CO1.PCCNTR.4832649",
        "referencia_del_contrato": "OC 012-2023",
        "estado_contrato": "Modificado",
        "codigo_de_categoria_principal": "V1.77101800",
        "descripcion_del_proceso": "INTERVENTORIA TECNICA;\nADMINISTRATIVA; LEGAL Y FINANCIERA\nPARA EL PROYECTO DE\nCONSTRUCCIÓN DEL CENTRO DIA Y DE\nPROTECCIÓN DEL ADULTO MAYOR EN\nEL MUNICIPIO DE MARMATO",
        "tipo_de_contrato": "Otro",
        "modalidad_de_contratacion": "Contratación régimen especial (con ofertas)",
        "justificacion_modalidad_de": "Regla aplicable",
        "fecha_de_firma": "2023-04-12T00:00:00.000",
        "fecha_de_inicio_del_contrato": "2023-04-12T00:00:00.000",
        "fecha_de_fin_del_contrato": "2023-11-27T00:00:00.000",
        "condiciones_de_entrega": "A convenir",
        "tipodocproveedor": "NIT",
        "documento_proveedor": "901543630",
        "proveedor_adjudicado": "OBRAS INTERVENTORIAS Y PROYECTOS OIP ZOMAC S.A.S",
        "es_grupo": "No",
        "es_pyme": "Si",
        "habilita_pago_adelantado": "No",
        "liquidaci_n": "No",
        "obligaci_n_ambiental": "No",
        "obligaciones_postconsumo": "No",
        "reversion": "No",
        "origen_de_los_recursos": "Distribuido",
        "destino_gasto": "Inversión",
        "valor_del_contrato": "289548129",
        "valor_de_pago_adelantado": "0",
        "valor_facturado": "0",
        "valor_pendiente_de_pago": "289548129",
        "valor_pagado": "0",
        "valor_amortizado": "0",
        "valor_pendiente_de": "0",
        "valor_pendiente_de_ejecucion": "289548129",
        "saldo_cdp": "289548129",
        "saldo_vigencia": "0",
        "espostconflicto": "No",
        "dias_adicionados": "47",
        "puntos_del_acuerdo": "No aplica",
        "pilares_del_acuerdo": "No aplica",
        "urlproceso": {
            "url": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.4229955&isFromPublicArea=True&isModal=true&asPopupView=true"
        },
        "nombre_representante_legal": "ERICA NATALIA LOPERA GONZALEZ",
        "nacionalidad_representante_legal": "CO",
        "domicilio_representante_legal": "Carrera 43 G 19 142",
        "tipo_de_identificaci_n_representante_legal": "Sin Descripcion",
        "identificaci_n_representante_legal": "Sin Descripcion",
        "g_nero_representante_legal": "Hombre",
        "presupuesto_general_de_la_nacion_pgn": "0",
        "sistema_general_de_participaciones": "0",
        "sistema_general_de_regal_as": "289548129",
        "recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_": "0",
        "recursos_de_credito": "0",
        "recursos_propios": "0",
        "ultima_actualizacion": "2023-10-06T00:00:00.000",
        "codigo_entidad": "713445724",
        "codigo_proveedor": "718765506",
        "objeto_del_contrato": "INTERVENTORIA TECNICA;\nADMINISTRATIVA; LEGAL Y FINANCIERA\nPARA EL PROYECTO DE\nCONSTRUCCIÓN DEL CENTRO DIA Y DE\nPROTECCIÓN DEL ADULTO MAYOR EN\nEL MUNICIPIO DE MARMATO",
        "duraci_n_del_contrato": "225 Dia(s)",
        "nombre_del_banco": "No definido",
        "tipo_de_cuenta": "No Definido",
        "n_mero_de_cuenta": "No definido",
        "el_contrato_puede_ser_prorrogado": "Si",
        "nombre_ordenador_del_gasto": "Velkis Neivany",
        "tipo_de_documento_ordenador_del_gasto": "Cédula de Ciudadanía",
        "n_mero_de_documento_ordenador_del_gasto": "1036929143",
        "nombre_supervisor": "Velkis Neivany",
        "tipo_de_documento_supervisor": "Cédula de Ciudadanía",
        "n_mero_de_documento_supervisor": "1036929143",
        "nombre_ordenador_de_pago": "No definido",
        "tipo_de_documento_ordenador_de_pago": "No definido",
        "n_mero_de_documento_ordenador_de_pago": "No definido",
        "documentos_tipo": "No",
        "descripcion_documentos_tipo": "No definido",
    },
    "e": {
        "nombre_entidad": "HOSPITAL DE AGUAZUL JUAN HERNANDO URREGO E.S.E",
        "nit_entidad": "844001355",
        "departamento": "Casanare",
        "ciudad": "Aguazul",
        "localizaci_n": "Colombia,  Casanare ,  Aguazul",
        "orden": "Territorial",
        "sector": "Salud y Protección Social",
        "rama": "Corporación Autónoma",
        "entidad_centralizada": "Centralizada",
        "proceso_de_compra": "CO1.BDOS.8610056",
        "id_contrato": "CO1.PCCNTR.8218834",
        "referencia_del_contrato": "443-2025",
        "estado_contrato": "Cerrado",
        "codigo_de_categoria_principal": "V1.85121608",
        "descripcion_del_proceso": "PRESTAR SERVICIOS PROFESIONALES EN PSICOLOGÍA PARA LA ATENCIÓN DE PACIENTES EN LOS DIFERENTES SERVICIOS ASISTENCIALES QUE OFERTA EL HOSPITAL DE AGUAZUL JUAN HERNANDO URREGO E.S.E.",
        "tipo_de_contrato": "Decreto 092 de 2017",
        "modalidad_de_contratacion": "Contratación régimen especial",
        "justificacion_modalidad_de": "Decreto 092 de 2017",
        "fecha_de_firma": "2025-08-21T00:00:00.000",
        "fecha_de_inicio_del_contrato": "2025-08-22T00:00:00.000",
        "fecha_de_fin_del_contrato": "2025-11-21T00:00:00.000",
        "condiciones_de_entrega": "NXTWY.DLVY.2",
        "tipodocproveedor": "Cédula de Ciudadanía",
        "documento_proveedor": "27603009",
        "proveedor_adjudicado": "CAROL ADRIANA FERNANDEZ RIVERA",
        "es_grupo": "No",
        "es_pyme": "No",
        "habilita_pago_adelantado": "No",
        "liquidaci_n": "No",
        "obligaci_n_ambiental": "No",
        "obligaciones_postconsumo": "No",
        "reversion": "No",
        "origen_de_los_recursos": "Recursos Propios",
        "destino_gasto": "Funcionamiento",
        "valor_del_contrato": "9446220",
        "valor_de_pago_adelantado": "0",
        "valor_facturado": "9446220",
        "valor_pendiente_de_pago": "0",
        "valor_pagado": "9446220",
        "valor_amortizado": "0",
        "valor_pendiente_de": "0",
        "valor_pendiente_de_ejecucion": "0",
        "saldo_cdp": "0",
        "saldo_vigencia": "0",
        "espostconflicto": "No",
        "dias_adicionados": "0",
        "puntos_del_acuerdo": "No aplica",
        "pilares_del_acuerdo": "No aplica",
        "urlproceso": {
            "url": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.8632910&isFromPublicArea=True&isModal=true&asPopupView=true"
        },
        "nombre_representante_legal": "CAROL ADRIANA FERNANDEZ RIVERA",
        "nacionalidad_representante_legal": "CO",
        "domicilio_representante_legal": "No Definido",
        "tipo_de_identificaci_n_representante_legal": "Sin Descripcion",
        "identificaci_n_representante_legal": "Sin Descripcion",
        "g_nero_representante_legal": "Mujer",
        "presupuesto_general_de_la_nacion_pgn": "0",
        "sistema_general_de_participaciones": "0",
        "sistema_general_de_regal_as": "0",
        "recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_": "0",
        "recursos_de_credito": "0",
        "recursos_propios": "9446220",
        "ultima_actualizacion": "2025-12-03T00:00:00.000",
        "codigo_entidad": "704254069",
        "codigo_proveedor": "720131960",
        "objeto_del_contrato": "PRESTAR SERVICIOS PROFESIONALES EN PSICOLOGÍA PARA LA ATENCIÓN DE PACIENTES EN LOS DIFERENTES SERVICIOS ASISTENCIALES QUE OFERTA EL HOSPITAL DE AGUAZUL JUAN HERNANDO URREGO E.S.E.",
        "duraci_n_del_contrato": "2 Mes(es)",
        "nombre_del_banco": "No definido",
        "tipo_de_cuenta": "No Definido",
        "n_mero_de_cuenta": "No definido",
        "el_contrato_puede_ser_prorrogado": "No",
        "nombre_ordenador_del_gasto": "NOHORA MARGARITA MENDOZA BUELVAS",
        "tipo_de_documento_ordenador_del_gasto": "Cédula de Ciudadanía",
        "n_mero_de_documento_ordenador_del_gasto": "50900069",
        "nombre_supervisor": "LEIDY GISELA ALVAREZ MESA",
        "tipo_de_documento_supervisor": "Cédula de Ciudadanía",
        "n_mero_de_documento_supervisor": "1049628601",
        "nombre_ordenador_de_pago": "No definido",
        "tipo_de_documento_ordenador_de_pago": "No definido",
        "n_mero_de_documento_ordenador_de_pago": "No definido",
        "documentos_tipo": "No",
        "descripcion_documentos_tipo": "No definido",
    },
    "f": {
        "nombre_entidad": "EMPRESA IBAGUEREÑA DE ACUEDUCTO Y ALCANTARILLADO SA ESP OFICIAL IBAL SA ESP OFICIAL",
        "nit_entidad": "8000898096",
        "departamento": "Tolima",
        "ciudad": "Ibagué",
        "localizaci_n": "Colombia,  Tolima ,  Ibagué",
        "orden": "Territorial",
        "sector": "No aplica/No pertenece",
        "rama": "Ejecutivo",
        "entidad_centralizada": "Descentralizada",
        "proceso_de_compra": "CO1.BDOS.8166384",
        "id_contrato": "CO1.PCCNTR.7911428",
        "referencia_del_contrato": "076 DE 2025",
        "estado_contrato": "En ejecución",
        "codigo_de_categoria_principal": "V1.72141120",
        "descripcion_del_proceso": "CONSTRUCCIÓN DE LAS REDES DE ALCANTARILLADO PRINCIPAL DE LA CALLE 37 ENTRE CARRERA 4C BIS Y AVENIDA FERROCARRIL D.N B/ NACIONAL EN EL MUNICIPIO DE IBAGUÉ",
        "tipo_de_contrato": "Obra",
        "modalidad_de_contratacion": "Contratación régimen especial",
        "justificacion_modalidad_de": "Regla aplicable",
        "fecha_de_firma": "2025-05-26T00:00:00.000",
        "fecha_de_inicio_del_contrato": "2025-06-16T00:00:00.000",
        "fecha_de_fin_del_contrato": "2025-09-13T00:00:00.000",
        "condiciones_de_entrega": "NXTWY.DLVY.2",
        "tipodocproveedor": "NIT",
        "documento_proveedor": "900322299",
        "proveedor_adjudicado": "CONSTRUCAM CONSTRUCCIONES S.A.S.",
        "es_grupo": "No",
        "es_pyme": "Si",
        "habilita_pago_adelantado": "No",
        "liquidaci_n": "Si",
        "obligaci_n_ambiental": "No",
        "obligaciones_postconsumo": "No",
        "reversion": "No",
        "origen_de_los_recursos": "Recursos Propios",
        "destino_gasto": "Inversión",
        "valor_del_contrato": "342935649",
        "valor_de_pago_adelantado": "0",
        "valor_facturado": "0",
        "valor_pendiente_de_pago": "342935649",
        "valor_pagado": "0",
        "valor_amortizado": "0",
        "valor_pendiente_de": "0",
        "valor_pendiente_de_ejecucion": "342935649",
        "saldo_cdp": "0",
        "saldo_vigencia": "0",
        "espostconflicto": "No",
        "dias_adicionados": "0",
        "puntos_del_acuerdo": "No aplica",
        "pilares_del_acuerdo": "No aplica",
        "urlproceso": {
            "url": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.8186580&isFromPublicArea=True&isModal=true&asPopupView=true"
        },
        "nombre_representante_legal": "CARLOS ALBERTO MAHECHA MORENO",
        "nacionalidad_representante_legal": "CO",
        "domicilio_representante_legal": "PASEO COMERCIAL ARKACENTRO OFICINA E2 - B19",
        "tipo_de_identificaci_n_representante_legal": "Cédula de Ciudadanía",
        "identificaci_n_representante_legal": "14238687",
        "g_nero_representante_legal": "Mujer",
        "presupuesto_general_de_la_nacion_pgn": "0",
        "sistema_general_de_participaciones": "0",
        "sistema_general_de_regal_as": "0",
        "recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_": "0",
        "recursos_de_credito": "0",
        "recursos_propios": "342935649",
        "codigo_entidad": "718300304",
        "codigo_proveedor": "700787252",
        "fecha_inicio_liquidacion": "2025-09-04T00:00:00.000",
        "fecha_fin_liquidacion": "2026-03-03T00:00:00.000",
        "objeto_del_contrato": "CONSTRUCCIÓN DE LAS REDES DE ALCANTARILLADO PRINCIPAL DE LA CALLE 37 ENTRE CARRERA 4C BIS Y AVENIDA FERROCARRIL D.N B/ NACIONAL EN EL MUNICIPIO DE IBAGUÉ",
        "duraci_n_del_contrato": "90 Dia(s)",
        "nombre_del_banco": "No definido",
        "tipo_de_cuenta": "No Definido",
        "n_mero_de_cuenta": "No definido",
        "el_contrato_puede_ser_prorrogado": "No",
        "nombre_ordenador_del_gasto": "No definido",
        "tipo_de_documento_ordenador_del_gasto": "No definido",
        "n_mero_de_documento_ordenador_del_gasto": "No definido",
        "nombre_supervisor": "No definido",
        "tipo_de_documento_supervisor": "No definido",
        "n_mero_de_documento_supervisor": "No definido",
        "nombre_ordenador_de_pago": "No definido",
        "tipo_de_documento_ordenador_de_pago": "No definido",
        "n_mero_de_documento_ordenador_de_pago": "No definido",
        "documentos_tipo": "No",
        "descripcion_documentos_tipo": "No definido",
    },
}

for key, value in dict.items():
    for key, value in value.items():
        if key == "ultima_actualizacion":
            print(value)
